<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <PackageId>DockPanelSuite.ThemeVS2015</PackageId>
    <PackageVersion>4.0.0</PackageVersion>
    <FileVersion>4.0.0.0</FileVersion>    
    <Authors>Weifen Luo and other contributors</Authors>
    <Description>Visual Studio 2015 themes for DockPanel Suite.</Description>
    <Copyright>(C) 2007-2025 Weifen Luo and other contributors</Copyright>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>http://dockpanelsuite.com</PackageProjectUrl>
    <PackageReleaseNotes>
      Release notes can be found at GitHub,
      https://github.com/dockpanelsuite/dockpanelsuite/releases
    </PackageReleaseNotes>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WeifenLuo.WinFormsUI.ThemeVS2015</RootNamespace>
    <AssemblyName>WeifenLuo.WinFormsUI.Docking.ThemeVS2015</AssemblyName>
    <EnableDefaultItems>true</EnableDefaultItems>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>dockpanelsuite.snk</AssemblyOriginatorKeyFile>
    <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Dockindicator_PaneDiamond_Hotspot.png" />
    <EmbeddedResource Include="Resources\DockIndicator_PaneDiamond_HotspotIndex.png" />
    <EmbeddedResource Include="Resources\MaskArrowBottom.png" />
    <EmbeddedResource Include="Resources\MaskArrowLeft.png" />
    <EmbeddedResource Include="Resources\MaskArrowRight.png" />
    <EmbeddedResource Include="Resources\MaskArrowTop.png" />
    <EmbeddedResource Include="Resources\MaskCoreBottom.png" />
    <EmbeddedResource Include="Resources\MaskCoreCenter.png" />
    <EmbeddedResource Include="Resources\MaskCoreLeft.png" />
    <EmbeddedResource Include="Resources\MaskCoreRight.png" />
    <EmbeddedResource Include="Resources\MaskCoreTop.png" />
    <EmbeddedResource Include="Resources\MaskDock.png" />
    <EmbeddedResource Include="Resources\MaskDockFive.png" />
    <EmbeddedResource Include="Resources\MaskTabClose.png" />
    <EmbeddedResource Include="Resources\MaskTabList.png" />
    <EmbeddedResource Include="Resources\MaskTabOverflow.png" />
    <EmbeddedResource Include="Resources\MaskToolWindowAutoHide.png" />
    <EmbeddedResource Include="Resources\MaskToolWindowClose.png" />
    <EmbeddedResource Include="Resources\MaskToolWindowDock.png" />
    <EmbeddedResource Include="Resources\MaskToolWindowOption.png" />
    <EmbeddedResource Include="Resources\MaskWindowBottom.png" />
    <EmbeddedResource Include="Resources\MaskWindowCenter.png" />
    <EmbeddedResource Include="Resources\MaskWindowLeft.png" />
    <EmbeddedResource Include="Resources\MaskWindowRight.png" />
    <EmbeddedResource Include="Resources\MaskWindowTop.png" />
    <EmbeddedResource Include="Resources\vs2015blue.vstheme.gz" />
    <EmbeddedResource Include="Resources\vs2015dark.vstheme.gz" />
    <EmbeddedResource Include="Resources\vs2015light.vstheme.gz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsUI\WinFormsUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
