<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <PackageId>DockPanelSuite.ThemeVS2015</PackageId>
    <PackageVersion>4.0.0</PackageVersion>
    <FileVersion>4.0.0.0</FileVersion>    
    <Authors>Weifen Luo and other contributors</Authors>
    <Description>Visual Studio 2015 themes for DockPanel Suite.</Description>
    <Copyright>(C) 2007-2025 Weifen Luo and other contributors</Copyright>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>http://dockpanelsuite.com</PackageProjectUrl>
    <PackageReleaseNotes>
      Release notes can be found at GitHub,
      https://github.com/dockpanelsuite/dockpanelsuite/releases
    </PackageReleaseNotes>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WeifenLuo.WinFormsUI.ThemeVS2015</RootNamespace>
    <AssemblyName>WeifenLuo.WinFormsUI.Docking.ThemeVS2015</AssemblyName>
    <EnableDefaultItems>true</EnableDefaultItems>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>dockpanelsuite.snk</AssemblyOriginatorKeyFile>
    <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsUI\WinFormsUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
