<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>DockPanelSuite.ThemeVS2015</PackageId>
    <PackageVersion>3.1.1</PackageVersion>
    <FileVersion>3.1.1.0</FileVersion>
    <Authors>Weifen Luo and other contributors</Authors>
    <Description>Visual Studio 2015 themes for DockPanel Suite.</Description>
    <Copyright>(C) 2007-2020 Weifen Luo and other contributors</Copyright>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>http://dockpanelsuite.com</PackageProjectUrl>
    <PackageReleaseNotes>
      Release notes can be found at GitHub,
      https://github.com/dockpanelsuite/dockpanelsuite/releases
    </PackageReleaseNotes>
    <TargetFrameworks>netcoreapp3.1;net40;net481</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject />
    <RootNamespace>WeifenLuo.WinFormsUI</RootNamespace>
    <AssemblyName>WeifenLuo.WinFormsUI.Docking.ThemeVS2015</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>dockpanelsuite.snk</AssemblyOriginatorKeyFile>
    <EnableDefaultItems>false</EnableDefaultItems>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ThemeVS2015\ImageService.cs" />
    <Compile Include="ThemeVS2015\PaintingService.cs" />
    <Compile Include="ThemeVS2015\Strings.Designer.cs">
      <DependentUpon>Strings.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Include="ThemeVS2015\VS2012AutoHideStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2012AutoHideStripFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012AutoHideWindowControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2012AutoHideWindowFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012DockIndicatorFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012DockOutlineFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012DockPaneCaptionInertButton.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2012DockWindow.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2012DockWindowFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012PaletteFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012PaneIndicatorFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012PanelIndicatorFactory.cs" />
    <Compile Include="ThemeVS2015\VS2012WindowSplitterControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2013DockPane.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2013DockPaneCaption.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2013DockPaneCaptionFactory.cs" />
    <Compile Include="ThemeVS2015\VS2013DockPaneFactory.cs" />
    <Compile Include="ThemeVS2015\VS2013DockPaneSplitterControlFactory.cs" />
    <Compile Include="ThemeVS2015\VS2013DockPaneStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2013DockPaneStripFactory.cs" />
    <Compile Include="ThemeVS2015\VS2013SplitterControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2013WindowSplitterControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2013WindowSplitterControlFactory.cs" />
    <Compile Include="ThemeVS2015\VS2015ThemeBase.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2015LightTheme.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2015DarkTheme.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ThemeVS2015\VS2015BlueTheme.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ThemeVS2015\Resources\Dockindicator_PaneDiamond_Hotspot.png" />
    <Content Include="ThemeVS2015\Resources\DockIndicator_PaneDiamond_HotspotIndex.png" />
    <Content Include="ThemeVS2015\Resources\MaskArrowBottom.png" />
    <Content Include="ThemeVS2015\Resources\MaskArrowLeft.png" />
    <Content Include="ThemeVS2015\Resources\MaskArrowRight.png" />
    <Content Include="ThemeVS2015\Resources\MaskArrowTop.png" />
    <Content Include="ThemeVS2015\Resources\MaskCoreBottom.png" />
    <Content Include="ThemeVS2015\Resources\MaskCoreCenter.png" />
    <Content Include="ThemeVS2015\Resources\MaskCoreLeft.png" />
    <Content Include="ThemeVS2015\Resources\MaskCoreRight.png" />
    <Content Include="ThemeVS2015\Resources\MaskCoreTop.png" />
    <Content Include="ThemeVS2015\Resources\MaskDock.png" />
    <Content Include="ThemeVS2015\Resources\MaskDockFive.png" />
    <Content Include="ThemeVS2015\Resources\MaskTabClose.png" />
    <Content Include="ThemeVS2015\Resources\MaskTabList.png" />
    <Content Include="ThemeVS2015\Resources\MaskTabOverflow.png" />
    <Content Include="ThemeVS2015\Resources\MaskToolWindowAutoHide.png" />
    <Content Include="ThemeVS2015\Resources\MaskToolWindowClose.png" />
    <Content Include="ThemeVS2015\Resources\MaskToolWindowDock.png" />
    <Content Include="ThemeVS2015\Resources\MaskToolWindowOption.png" />
    <Content Include="ThemeVS2015\Resources\MaskWindowBottom.png" />
    <Content Include="ThemeVS2015\Resources\MaskWindowCenter.png" />
    <Content Include="ThemeVS2015\Resources\MaskWindowLeft.png" />
    <Content Include="ThemeVS2015\Resources\MaskWindowRight.png" />
    <Content Include="ThemeVS2015\Resources\MaskWindowTop.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ThemeVS2015\Strings.resx">
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="dockpanelsuite.snk" />
    <None Include="license.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="ThemeVS2015\Resources\vs2015blue.vstheme.gz" />
    <None Include="ThemeVS2015\Resources\vs2015dark.vstheme.gz" />
    <None Include="ThemeVS2015\Resources\vs2015light.vstheme.gz" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="WinFormsUI.csproj" />
  </ItemGroup>

</Project>
